language: go

os:
  - linux
  - osx

go:
  - 1.12.x

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go get -t github.com/codeclimate/test-reporter; fi

install:
  - make all wezen wetool

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test-reporter before-build; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make cover-check; fi

after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

before_deploy:
  - MEYCOIN_VERSION="${TRAVIS_TAG:1}"
  - mkdir -p release
  - mkdir -p meycoin/${MEYCOIN_VERSION}/bin
  - mkdir -p meycoin/${MEYCOIN_VERSION}/lib
  - mv bin/{meycoincli,meycoinluac,meycoinsvr,brick} meycoin/${MEYCOIN_VERSION}/bin
  - cp libtool/lib/libgmp* meycoin/${MEYCOIN_VERSION}/lib
  - tar -zcvf release/mey-${MEYCOIN_VERSION}.${TRAVIS_OS_NAME}.tar.gz meycoin/${MEYCOIN_VERSION}
  - mkdir -p wezen/${MEYCOIN_VERSION}/bin
  - mkdir -p wezen/${MEYCOIN_VERSION}/lib
  - mv bin/{wezen,wetool} wezen/${MEYCOIN_VERSION}/bin
  - cp libtool/lib/libgmp* wezen/${MEYCOIN_VERSION}/lib
  - tar -zcvf release/wezen-${MEYCOIN_VERSION}.${TRAVIS_OS_NAME}.tar.gz wezen/${MEYCOIN_VERSION}

deploy:
  provider: releases
  api_key:
    secure: uGFdnqc23aUqoZD9bZqQsGl4KiHAH6WkUrH9mrdgzsb5sXaChhX0J9klJcDEbYOKG19HUeoBHSorwSKl6Bsg+eOqf8E+blNQLNq7CoPcceGkpXBrfmGe3zgXKjrEGDbsEBuR7oA4GcJAYKw+tJEXZ7z4jy6kuJFxn5j3MZqvz0XIKM6/dUiF/0N1sfLrDWWpdBrW2yJt9yHaeqXhhA/IiHVrlj79KYxTU0UFwdBW6CjxLpOoQWaFwW3X94l5/UpKrDXFpwjjCOhceBpm8dHBxbYujDtop/n/R0VdhtVXtdyx/I877e/d5z3fDL6xTuAMnDYbJdqhVVbBoAukbOpYzhksJ7+1dFFEcku6pFfYPMnxjhxNs9AN5b/qAdxauUe167a/XVUOyOUFoZlptZsGO5i9HXCAnLOgyyTMpeeo3ELIJvSQAK5J9l/wz1g0cJboRsu1rM0LmNqynzScJja2MWaH1vXKlFA56Lr0ZtY/N3T7pg+BPucFp4Fp8hedoEIqRZbqWDAlfX4aY8u6BWTS5929ThrXT9Y5PRZplLAW9QdlmHewWZpevCSm5HA60SF7Qz9tUAVTyKzx/GLvLBNyI82M9JggHwK0gVe/fU0NtKewZnwNaJ4uM5LZvJxq6h0+/N6BLBZsLmBbUC3BgodMSdxb9y0rG8ipAWi9dZhEYd0=
  file_glob: true
  file: release/*
  skip_cleanup: true
  draft: true 
  on:
    tags: true
