FROM golang:1.12.5-alpine3.9 as builder
RUN apk update && apk add git cmake build-base m4
COPY . meycoin
RUN cd meycoin && make meycoincli meycoinluac brick

FROM alpine:3.9
RUN apk add libgcc
COPY --from=builder /go/meycoin/bin/* /usr/local/bin/
COPY --from=builder /go/meycoin/cmd/brick/arglog.toml /tools/arglog.toml
COPY --from=builder /go/meycoin/libtool/lib/* /usr/local/lib/
ENV LD_LIBRARY_PATH="/usr/local/lib:${LD_LIBRARY_PATH}"
WORKDIR /tools/
CMD ["meycoincli"]
