// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/meeypioneer/meycoin/types (interfaces: MeyCoinRPCServiceClient)

// Package mock_types is a generated GoMock package.
package mock_types

import (
	context "context"
	reflect "reflect"

	types "github.com/meeypioneer/meycoin/types"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockMeyCoinRPCServiceClient is a mock of MeyCoinRPCServiceClient interface
type MockMeyCoinRPCServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockMeyCoinRPCServiceClientMockRecorder
}

// MockMeyCoinRPCServiceClientMockRecorder is the mock recorder for MockMeyCoinRPCServiceClient
type MockMeyCoinRPCServiceClientMockRecorder struct {
	mock *MockMeyCoinRPCServiceClient
}

// NewMockMeyCoinRPCServiceClient creates a new mock instance
func NewMockMeyCoinRPCServiceClient(ctrl *gomock.Controller) *MockMeyCoinRPCServiceClient {
	mock := &MockMeyCoinRPCServiceClient{ctrl: ctrl}
	mock.recorder = &MockMeyCoinRPCServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMeyCoinRPCServiceClient) EXPECT() *MockMeyCoinRPCServiceClientMockRecorder {
	return m.recorder
}

// Blockchain mocks base method
func (m *MockMeyCoinRPCServiceClient) Blockchain(arg0 context.Context, arg1 *types.Empty, arg2 ...grpc.CallOption) (*types.BlockchainStatus, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Blockchain", varargs...)
	ret0, _ := ret[0].(*types.BlockchainStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Blockchain indicates an expected call of Blockchain
func (mr *MockMeyCoinRPCServiceClientMockRecorder) Blockchain(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blockchain", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).Blockchain), varargs...)
}

// ChainStat mocks base method
func (m *MockMeyCoinRPCServiceClient) ChainStat(arg0 context.Context, arg1 *types.Empty, arg2 ...grpc.CallOption) (*types.ChainStats, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ChainStat", varargs...)
	ret0, _ := ret[0].(*types.ChainStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChainStat indicates an expected call of ChainStat
func (mr *MockMeyCoinRPCServiceClientMockRecorder) ChainStat(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChainStat", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).ChainStat), varargs...)
}

// ChangeMembership mocks base method
func (m *MockMeyCoinRPCServiceClient) ChangeMembership(arg0 context.Context, arg1 *types.MembershipChange, arg2 ...grpc.CallOption) (*types.MembershipChangeReply, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ChangeMembership", varargs...)
	ret0, _ := ret[0].(*types.MembershipChangeReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeMembership indicates an expected call of ChangeMembership
func (mr *MockMeyCoinRPCServiceClientMockRecorder) ChangeMembership(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeMembership", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).ChangeMembership), varargs...)
}

// CommitTX mocks base method
func (m *MockMeyCoinRPCServiceClient) CommitTX(arg0 context.Context, arg1 *types.TxList, arg2 ...grpc.CallOption) (*types.CommitResultList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitTX", varargs...)
	ret0, _ := ret[0].(*types.CommitResultList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitTX indicates an expected call of CommitTX
func (mr *MockMeyCoinRPCServiceClientMockRecorder) CommitTX(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTX", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).CommitTX), varargs...)
}

// CreateAccount mocks base method
func (m *MockMeyCoinRPCServiceClient) CreateAccount(arg0 context.Context, arg1 *types.Personal, arg2 ...grpc.CallOption) (*types.Account, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateAccount", varargs...)
	ret0, _ := ret[0].(*types.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount
func (mr *MockMeyCoinRPCServiceClientMockRecorder) CreateAccount(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).CreateAccount), varargs...)
}

// ExportAccount mocks base method
func (m *MockMeyCoinRPCServiceClient) ExportAccount(arg0 context.Context, arg1 *types.Personal, arg2 ...grpc.CallOption) (*types.SingleBytes, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExportAccount", varargs...)
	ret0, _ := ret[0].(*types.SingleBytes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportAccount indicates an expected call of ExportAccount
func (mr *MockMeyCoinRPCServiceClientMockRecorder) ExportAccount(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportAccount", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).ExportAccount), varargs...)
}

// ExportAccountKeystore mocks base method
func (m *MockMeyCoinRPCServiceClient) ExportAccountKeystore(arg0 context.Context, arg1 *types.Personal, arg2 ...grpc.CallOption) (*types.SingleBytes, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExportAccountKeystore", varargs...)
	ret0, _ := ret[0].(*types.SingleBytes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportAccountKeystore indicates an expected call of ExportAccountKeystore
func (mr *MockMeyCoinRPCServiceClientMockRecorder) ExportAccountKeystore(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportAccountKeystore", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).ExportAccountKeystore), varargs...)
}

// GetABI mocks base method
func (m *MockMeyCoinRPCServiceClient) GetABI(arg0 context.Context, arg1 *types.SingleBytes, arg2 ...grpc.CallOption) (*types.ABI, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetABI", varargs...)
	ret0, _ := ret[0].(*types.ABI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetABI indicates an expected call of GetABI
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetABI(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetABI", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetABI), varargs...)
}

// GetAccountVotes mocks base method
func (m *MockMeyCoinRPCServiceClient) GetAccountVotes(arg0 context.Context, arg1 *types.AccountAddress, arg2 ...grpc.CallOption) (*types.AccountVoteInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccountVotes", varargs...)
	ret0, _ := ret[0].(*types.AccountVoteInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountVotes indicates an expected call of GetAccountVotes
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetAccountVotes(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountVotes", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetAccountVotes), varargs...)
}

// GetAccounts mocks base method
func (m *MockMeyCoinRPCServiceClient) GetAccounts(arg0 context.Context, arg1 *types.Empty, arg2 ...grpc.CallOption) (*types.AccountList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccounts", varargs...)
	ret0, _ := ret[0].(*types.AccountList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccounts indicates an expected call of GetAccounts
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetAccounts(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccounts", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetAccounts), varargs...)
}

// GetBlock mocks base method
func (m *MockMeyCoinRPCServiceClient) GetBlock(arg0 context.Context, arg1 *types.SingleBytes, arg2 ...grpc.CallOption) (*types.Block, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBlock", varargs...)
	ret0, _ := ret[0].(*types.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlock indicates an expected call of GetBlock
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetBlock(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlock", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetBlock), varargs...)
}

// GetBlockBody mocks base method
func (m *MockMeyCoinRPCServiceClient) GetBlockBody(arg0 context.Context, arg1 *types.BlockBodyParams, arg2 ...grpc.CallOption) (*types.BlockBodyPaged, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBlockBody", varargs...)
	ret0, _ := ret[0].(*types.BlockBodyPaged)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockBody indicates an expected call of GetBlockBody
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetBlockBody(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockBody", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetBlockBody), varargs...)
}

// GetBlockMetadata mocks base method
func (m *MockMeyCoinRPCServiceClient) GetBlockMetadata(arg0 context.Context, arg1 *types.SingleBytes, arg2 ...grpc.CallOption) (*types.BlockMetadata, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBlockMetadata", varargs...)
	ret0, _ := ret[0].(*types.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockMetadata indicates an expected call of GetBlockMetadata
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetBlockMetadata(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockMetadata", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetBlockMetadata), varargs...)
}

// GetBlockTX mocks base method
func (m *MockMeyCoinRPCServiceClient) GetBlockTX(arg0 context.Context, arg1 *types.SingleBytes, arg2 ...grpc.CallOption) (*types.TxInBlock, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBlockTX", varargs...)
	ret0, _ := ret[0].(*types.TxInBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockTX indicates an expected call of GetBlockTX
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetBlockTX(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockTX", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetBlockTX), varargs...)
}

// GetChainInfo mocks base method
func (m *MockMeyCoinRPCServiceClient) GetChainInfo(arg0 context.Context, arg1 *types.Empty, arg2 ...grpc.CallOption) (*types.ChainInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetChainInfo", varargs...)
	ret0, _ := ret[0].(*types.ChainInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChainInfo indicates an expected call of GetChainInfo
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetChainInfo(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChainInfo", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetChainInfo), varargs...)
}

// GetConfChangeProgress mocks base method
func (m *MockMeyCoinRPCServiceClient) GetConfChangeProgress(arg0 context.Context, arg1 *types.SingleBytes, arg2 ...grpc.CallOption) (*types.ConfChangeProgress, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetConfChangeProgress", varargs...)
	ret0, _ := ret[0].(*types.ConfChangeProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfChangeProgress indicates an expected call of GetConfChangeProgress
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetConfChangeProgress(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfChangeProgress", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetConfChangeProgress), varargs...)
}

// GetConsensusInfo mocks base method
func (m *MockMeyCoinRPCServiceClient) GetConsensusInfo(arg0 context.Context, arg1 *types.Empty, arg2 ...grpc.CallOption) (*types.ConsensusInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetConsensusInfo", varargs...)
	ret0, _ := ret[0].(*types.ConsensusInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsensusInfo indicates an expected call of GetConsensusInfo
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetConsensusInfo(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsensusInfo", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetConsensusInfo), varargs...)
}

// GetEnterpriseConfig mocks base method
func (m *MockMeyCoinRPCServiceClient) GetEnterpriseConfig(arg0 context.Context, arg1 *types.EnterpriseConfigKey, arg2 ...grpc.CallOption) (*types.EnterpriseConfig, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetEnterpriseConfig", varargs...)
	ret0, _ := ret[0].(*types.EnterpriseConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnterpriseConfig indicates an expected call of GetEnterpriseConfig
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetEnterpriseConfig(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnterpriseConfig", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetEnterpriseConfig), varargs...)
}

// GetNameInfo mocks base method
func (m *MockMeyCoinRPCServiceClient) GetNameInfo(arg0 context.Context, arg1 *types.Name, arg2 ...grpc.CallOption) (*types.NameInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetNameInfo", varargs...)
	ret0, _ := ret[0].(*types.NameInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNameInfo indicates an expected call of GetNameInfo
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetNameInfo(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNameInfo", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetNameInfo), varargs...)
}

// GetPeers mocks base method
func (m *MockMeyCoinRPCServiceClient) GetPeers(arg0 context.Context, arg1 *types.PeersParams, arg2 ...grpc.CallOption) (*types.PeerList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPeers", varargs...)
	ret0, _ := ret[0].(*types.PeerList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeers indicates an expected call of GetPeers
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetPeers(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeers", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetPeers), varargs...)
}

// GetReceipt mocks base method
func (m *MockMeyCoinRPCServiceClient) GetReceipt(arg0 context.Context, arg1 *types.SingleBytes, arg2 ...grpc.CallOption) (*types.Receipt, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetReceipt", varargs...)
	ret0, _ := ret[0].(*types.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceipt indicates an expected call of GetReceipt
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetReceipt(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceipt", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetReceipt), varargs...)
}

// GetServerInfo mocks base method
func (m *MockMeyCoinRPCServiceClient) GetServerInfo(arg0 context.Context, arg1 *types.KeyParams, arg2 ...grpc.CallOption) (*types.ServerInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetServerInfo", varargs...)
	ret0, _ := ret[0].(*types.ServerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerInfo indicates an expected call of GetServerInfo
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetServerInfo(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerInfo", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetServerInfo), varargs...)
}

// GetStaking mocks base method
func (m *MockMeyCoinRPCServiceClient) GetStaking(arg0 context.Context, arg1 *types.AccountAddress, arg2 ...grpc.CallOption) (*types.Staking, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStaking", varargs...)
	ret0, _ := ret[0].(*types.Staking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStaking indicates an expected call of GetStaking
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetStaking(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStaking", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetStaking), varargs...)
}

// GetState mocks base method
func (m *MockMeyCoinRPCServiceClient) GetState(arg0 context.Context, arg1 *types.SingleBytes, arg2 ...grpc.CallOption) (*types.State, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetState", varargs...)
	ret0, _ := ret[0].(*types.State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetState indicates an expected call of GetState
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetState(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetState), varargs...)
}

// GetStateAndProof mocks base method
func (m *MockMeyCoinRPCServiceClient) GetStateAndProof(arg0 context.Context, arg1 *types.AccountAndRoot, arg2 ...grpc.CallOption) (*types.AccountProof, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStateAndProof", varargs...)
	ret0, _ := ret[0].(*types.AccountProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStateAndProof indicates an expected call of GetStateAndProof
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetStateAndProof(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStateAndProof", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetStateAndProof), varargs...)
}

// GetTX mocks base method
func (m *MockMeyCoinRPCServiceClient) GetTX(arg0 context.Context, arg1 *types.SingleBytes, arg2 ...grpc.CallOption) (*types.Tx, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTX", varargs...)
	ret0, _ := ret[0].(*types.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTX indicates an expected call of GetTX
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetTX(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTX", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetTX), varargs...)
}

// GetVotes mocks base method
func (m *MockMeyCoinRPCServiceClient) GetVotes(arg0 context.Context, arg1 *types.VoteParams, arg2 ...grpc.CallOption) (*types.VoteList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetVotes", varargs...)
	ret0, _ := ret[0].(*types.VoteList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVotes indicates an expected call of GetVotes
func (mr *MockMeyCoinRPCServiceClientMockRecorder) GetVotes(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVotes", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).GetVotes), varargs...)
}

// ImportAccount mocks base method
func (m *MockMeyCoinRPCServiceClient) ImportAccount(arg0 context.Context, arg1 *types.ImportFormat, arg2 ...grpc.CallOption) (*types.Account, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ImportAccount", varargs...)
	ret0, _ := ret[0].(*types.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportAccount indicates an expected call of ImportAccount
func (mr *MockMeyCoinRPCServiceClientMockRecorder) ImportAccount(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportAccount", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).ImportAccount), varargs...)
}

// ListBlockHeaders mocks base method
func (m *MockMeyCoinRPCServiceClient) ListBlockHeaders(arg0 context.Context, arg1 *types.ListParams, arg2 ...grpc.CallOption) (*types.BlockHeaderList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListBlockHeaders", varargs...)
	ret0, _ := ret[0].(*types.BlockHeaderList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlockHeaders indicates an expected call of ListBlockHeaders
func (mr *MockMeyCoinRPCServiceClientMockRecorder) ListBlockHeaders(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlockHeaders", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).ListBlockHeaders), varargs...)
}

// ListBlockMetadata mocks base method
func (m *MockMeyCoinRPCServiceClient) ListBlockMetadata(arg0 context.Context, arg1 *types.ListParams, arg2 ...grpc.CallOption) (*types.BlockMetadataList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListBlockMetadata", varargs...)
	ret0, _ := ret[0].(*types.BlockMetadataList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlockMetadata indicates an expected call of ListBlockMetadata
func (mr *MockMeyCoinRPCServiceClientMockRecorder) ListBlockMetadata(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlockMetadata", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).ListBlockMetadata), varargs...)
}

// ListBlockMetadataStream mocks base method
func (m *MockMeyCoinRPCServiceClient) ListBlockMetadataStream(arg0 context.Context, arg1 *types.Empty, arg2 ...grpc.CallOption) (types.MeyCoinRPCService_ListBlockMetadataStreamClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListBlockMetadataStream", varargs...)
	ret0, _ := ret[0].(types.MeyCoinRPCService_ListBlockMetadataStreamClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlockMetadataStream indicates an expected call of ListBlockMetadataStream
func (mr *MockMeyCoinRPCServiceClientMockRecorder) ListBlockMetadataStream(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlockMetadataStream", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).ListBlockMetadataStream), varargs...)
}

// ListBlockStream mocks base method
func (m *MockMeyCoinRPCServiceClient) ListBlockStream(arg0 context.Context, arg1 *types.Empty, arg2 ...grpc.CallOption) (types.MeyCoinRPCService_ListBlockStreamClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListBlockStream", varargs...)
	ret0, _ := ret[0].(types.MeyCoinRPCService_ListBlockStreamClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlockStream indicates an expected call of ListBlockStream
func (mr *MockMeyCoinRPCServiceClientMockRecorder) ListBlockStream(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlockStream", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).ListBlockStream), varargs...)
}

// ListEventStream mocks base method
func (m *MockMeyCoinRPCServiceClient) ListEventStream(arg0 context.Context, arg1 *types.FilterInfo, arg2 ...grpc.CallOption) (types.MeyCoinRPCService_ListEventStreamClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListEventStream", varargs...)
	ret0, _ := ret[0].(types.MeyCoinRPCService_ListEventStreamClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEventStream indicates an expected call of ListEventStream
func (mr *MockMeyCoinRPCServiceClientMockRecorder) ListEventStream(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEventStream", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).ListEventStream), varargs...)
}

// ListEvents mocks base method
func (m *MockMeyCoinRPCServiceClient) ListEvents(arg0 context.Context, arg1 *types.FilterInfo, arg2 ...grpc.CallOption) (*types.EventList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListEvents", varargs...)
	ret0, _ := ret[0].(*types.EventList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents
func (mr *MockMeyCoinRPCServiceClientMockRecorder) ListEvents(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).ListEvents), varargs...)
}

// LockAccount mocks base method
func (m *MockMeyCoinRPCServiceClient) LockAccount(arg0 context.Context, arg1 *types.Personal, arg2 ...grpc.CallOption) (*types.Account, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LockAccount", varargs...)
	ret0, _ := ret[0].(*types.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockAccount indicates an expected call of LockAccount
func (mr *MockMeyCoinRPCServiceClientMockRecorder) LockAccount(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockAccount", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).LockAccount), varargs...)
}

// Metric mocks base method
func (m *MockMeyCoinRPCServiceClient) Metric(arg0 context.Context, arg1 *types.MetricsRequest, arg2 ...grpc.CallOption) (*types.Metrics, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Metric", varargs...)
	ret0, _ := ret[0].(*types.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Metric indicates an expected call of Metric
func (mr *MockMeyCoinRPCServiceClientMockRecorder) Metric(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metric", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).Metric), varargs...)
}

// NodeState mocks base method
func (m *MockMeyCoinRPCServiceClient) NodeState(arg0 context.Context, arg1 *types.NodeReq, arg2 ...grpc.CallOption) (*types.SingleBytes, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NodeState", varargs...)
	ret0, _ := ret[0].(*types.SingleBytes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NodeState indicates an expected call of NodeState
func (mr *MockMeyCoinRPCServiceClientMockRecorder) NodeState(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeState", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).NodeState), varargs...)
}

// QueryContract mocks base method
func (m *MockMeyCoinRPCServiceClient) QueryContract(arg0 context.Context, arg1 *types.Query, arg2 ...grpc.CallOption) (*types.SingleBytes, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryContract", varargs...)
	ret0, _ := ret[0].(*types.SingleBytes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryContract indicates an expected call of QueryContract
func (mr *MockMeyCoinRPCServiceClientMockRecorder) QueryContract(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryContract", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).QueryContract), varargs...)
}

// QueryContractState mocks base method
func (m *MockMeyCoinRPCServiceClient) QueryContractState(arg0 context.Context, arg1 *types.StateQuery, arg2 ...grpc.CallOption) (*types.StateQueryProof, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryContractState", varargs...)
	ret0, _ := ret[0].(*types.StateQueryProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryContractState indicates an expected call of QueryContractState
func (mr *MockMeyCoinRPCServiceClientMockRecorder) QueryContractState(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryContractState", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).QueryContractState), varargs...)
}

// SendTX mocks base method
func (m *MockMeyCoinRPCServiceClient) SendTX(arg0 context.Context, arg1 *types.Tx, arg2 ...grpc.CallOption) (*types.CommitResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendTX", varargs...)
	ret0, _ := ret[0].(*types.CommitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendTX indicates an expected call of SendTX
func (mr *MockMeyCoinRPCServiceClientMockRecorder) SendTX(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTX", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).SendTX), varargs...)
}

// SignTX mocks base method
func (m *MockMeyCoinRPCServiceClient) SignTX(arg0 context.Context, arg1 *types.Tx, arg2 ...grpc.CallOption) (*types.Tx, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SignTX", varargs...)
	ret0, _ := ret[0].(*types.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignTX indicates an expected call of SignTX
func (mr *MockMeyCoinRPCServiceClientMockRecorder) SignTX(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignTX", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).SignTX), varargs...)
}

// UnlockAccount mocks base method
func (m *MockMeyCoinRPCServiceClient) UnlockAccount(arg0 context.Context, arg1 *types.Personal, arg2 ...grpc.CallOption) (*types.Account, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnlockAccount", varargs...)
	ret0, _ := ret[0].(*types.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlockAccount indicates an expected call of UnlockAccount
func (mr *MockMeyCoinRPCServiceClientMockRecorder) UnlockAccount(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockAccount", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).UnlockAccount), varargs...)
}

// VerifyTX mocks base method
func (m *MockMeyCoinRPCServiceClient) VerifyTX(arg0 context.Context, arg1 *types.Tx, arg2 ...grpc.CallOption) (*types.VerifyResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "VerifyTX", varargs...)
	ret0, _ := ret[0].(*types.VerifyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyTX indicates an expected call of VerifyTX
func (mr *MockMeyCoinRPCServiceClientMockRecorder) VerifyTX(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyTX", reflect.TypeOf((*MockMeyCoinRPCServiceClient)(nil).VerifyTX), varargs...)
}
