datadir = "/meycoin/data"
enableprofile = false
profileport = 6060
enabletestmode = true

[rpc]
netserviceaddr = "0.0.0.0"
netserviceport = 7845
nstls = false
nscert = ""
nskey = ""
nsallowcors = false

[p2p]
netprotocoladdr = "127.0.0.1"
netprotocolport = 7846
npbindaddr = "0.0.0.0"
npbindport = 7846
nptls = false
npcert = ""
npkey = ""
npaddpeers = [
]
npmaxpeers = "0"
nppeerpool = "0"
npusewezen = false

[mempool]
showmetrics = false
dumpfilepath = "/meycoin/mempool.dump"

[consensus]
enablebp = true
enabledpos = false
blockinterval = 1

